### ISSUE TITLE
Do next release with all crates at the same version

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/release#130]
See https://www.reddit.com/r/rust/comments/hl5778/new_gtkrs_release_new_crates_better_apis/fwx9o29/

It's simply confusing for users which versions of the many crates correspond to each other. We could easily make their live simpler (and probably also the release script) by doing the next release as `0.14.0` for all crates.

Means skipping some versions for everything but `gdk`, but who cares :)

I'm doing the same for gstreamer-rs as otherwise it's just too annoying to keep track of what the corresponding versions are, even for me as the maintainer.

**Comment by GuillaumeGomez** [comment]
It can be done simply by changing the version in all master branches to `0.13`.
