### ISSUE TITLE
Project icon

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/release#138]
I have got a deal with the GNOME design team to design us a logo in exchange for some code :P I opened this issue here to discuss that & offer feedback directly to @bertob 

The first iteration suggested by Tobias looks like this
![image](https://user-images.githubusercontent.com/7660997/106184871-690d2f00-61a2-11eb-8b64-1e947ce02244.png)

cc @sdroege @GuillaumeGomez

In my opinion: I like the use of :crab:  but maybe make the hexagonal a cube instead, not necessarily the same cube as the gtk one for trademark reasons

**Comment by GuillaumeGomez** [comment]
Nice! :D

**Comment by sdroege** [comment]
What's the trademark situation with ferris?

**Comment by bilelmoussaoui** [comment]
From a quick research the ferris is not trademarked https://twitter.com/rustlang/status/1141011659680559104 but public domain :) rustls seems to use it as a base for their logo as well
![image](https://user-images.githubusercontent.com/7660997/106192689-d2923b00-61ac-11eb-8578-1ef3582f1711.png)

**Comment by sdroege** [comment]
Sounds good then :)

> rustls seems to use it as a base for their logo as well

Well there are also projects using the (definitely trademark) Rust gears logo, or the GNOME foot or GTK boxes. It's just that nobody complained hard enough to those projects.

**Comment by bilelmoussaoui** [comment]
> Sounds good then :)
> 
> > rustls seems to use it as a base for their logo as well
> 
> Well there are also projects using the (definitely trademark) Rust gears logo, or the GNOME foot or GTK boxes. It's just that nobody complained hard enough to those projects.

It seems the GNOME designers are trying to setup some kind of libraries "logos" design guidelines, we can just use that (see the suggestion of Tobias) and avoid using the GTK boxes to stay away from any possible issues in the future

**Comment by sophie-h** [comment]
@bertob We are currently thinking about a website overhaul (gtk-rs/gtk-rs.github.io#204). Is there a chance that you could update the project logo displayed in this issue to the new GNOME standards? Also having the white ferris icon as svg for the website would probably be neat.

**Comment by bertob** [comment]
In the mean time our thinking on library logos has changed somewhat. The new plan is to basically have a regular symbolic icon for each library, and just use that on a circle (or other shape, depending on the context) with a background color or gradient. We already rolled this out for libadwaita, here's and example what it could look like for gtk-rs:

![image](https://user-images.githubusercontent.com/1908896/120724644-86496580-c4d4-11eb-93de-740d713aeaa2.png)

**Comment by sophie-h** [comment]
I must say ferris is looking gorgeous today! I really like you stylized version of :crab: and the more I look on the logo the more I like it.

I also like the new approach since it work quite good as chat logo etc. ![32](https://user-images.githubusercontent.com/3466497/120768103-1b238180-c51c-11eb-8bce-8d9c3e48cb01.png)

One thing I was wondering: Do you have any idea for slight variation of the logo? We currently have a separation in **Core**, **GTK 3** and **GTK 4** in the project. [The docs](https://gtk-rs.org/gtk-rs-core/git/docs/) for example use a 100x100px logo. I was wondering if we could add some visual cue to guide users through this structure? But that's super optional.

**Comment by GuillaumeGomez** [comment]
The logo looks nice!

> One thing I was wondering: Do you have any idea for slight variation of the logo? We currently have a separation in Core, GTK 3 and GTK 4 in the project. The docs for example use a 100x100px logo. I was wondering if we could add some visual clue to guide users through this structure? But that's super optional.

Why would you want a slight modification of each repository? Sounds a bit strange no?

**Comment by sophie-h** [comment]
> Why would you want a slight modification of each repository? Sounds a bit strange no?

I was thinking about people being confused at which docs they are currently looking. But yeah, just an idea. Also we hopefully reduced the confusion with the docs a lot with no longer linking GTK 3 from GTK 4 docs. Probably my idea stems from that time.

**Comment by sdroege** [comment]
OOC, which part of the logo is referring to GNOME or GTK? That looks like a generic Rust logo to me :) But otherwise looks nice.

**Comment by sophie-h** [comment]
> which part of the logo is referring to GNOME or GTK

If we want to keep ferris (and I think we should keep her), maybe we could choose a non-ferris associated color? I would consider yellow, orange, red to be in the original ferris range. That would leave us with blue and purple (imo xD). I would try blue because that's the most GNOMEish it get's with colors.

![Screenshot-20210604104351-252x492](https://user-images.githubusercontent.com/3466497/120773908-06e28300-c522-11eb-9194-18e2184b6212.png)

**Comment by sophie-h** [comment]
Blue with website context:

![download (19)](https://user-images.githubusercontent.com/3466497/120795587-f938f780-c539-11eb-9ed1-9720cf35bacc.png)

---
---

![download (18)](https://user-images.githubusercontent.com/3466497/120795595-f9d18e00-c539-11eb-80c8-ced8fbab8e7d.png)

---
---

![download (17)](https://user-images.githubusercontent.com/3466497/120795600-fa6a2480-c539-11eb-9c4b-695cc1a5dfd6.png)

**Comment by GuillaumeGomez** [comment]
Bikeshedding and personal tase, the comeback: I like the icon in blue, but I don't like the blue you picked for the header... XD

**Comment by sdroege** [comment]
Which of the blues? There are two variants (I like them both FWIW, maybe the dark one a bit more).

**Comment by GuillaumeGomez** [comment]
Ah the first one, didn't see the second screenshot. ><

Yes, the second one looks good.

**Comment by GuillaumeGomez** [comment]
Something I just thought about: how does the logo render on ayu and dark theme? I don't expect issues on the dark theme, however on the ayu one...

**Comment by sophie-h** [comment]
> Something I just thought about: how does the logo render on ayu and dark theme? I don't expect issues on the dark theme, however on the ayu one...

"Don't theme my website!"

Sorry, I don't get what you are talking about.

**Comment by GuillaumeGomez** [comment]
I don't want themes on gtk-rs.org, don't worry. ;) I was talking about rustdoc pages (since I assume we will use the logo there as well).

**Comment by bertob** [comment]
> which part of the logo is referring to GNOME or GTK? That looks like a generic Rust logo to me

I don't think we need to hit people over the head with GNOME/GTK-ness here, I think the glyph being in the style of our symbolics is enough.

No strong opinion about colors. I went with the red because it looked Rust-adjacent, but anything from the palette could probably work.

**Comment by sophie-h** [comment]
The red logo would certainly work. But I get the argument that it looks like a general rust logo.

![download (20)](https://user-images.githubusercontent.com/3466497/120800868-bc243380-c540-11eb-9df5-1b9571657c94.png)

**Comment by bilelmoussaoui** [comment]
> > which part of the logo is referring to GNOME or GTK? That looks like a generic Rust logo to me
> 
> I don't think we need to hit people over the head with GNOME/GTK-ness here, I think the glyph being in the style of our symbolics is enough.

The logo isn't about GTK-rs (as in the rust bindings of GTK) itself neither. Because there are bindings of other core libraries like Pango, Cairo, GLib/Gio. The suggested logo as is doesn't really tell anything other than hey it's a rust related thing.

**Comment by bertob** [comment]
It's a Rust-related thing using the GNOME library icon style and colors :)

You don't want every one of our libraries to have to make a super obvious reference to GTK/GNOME, that gets tired very quickly.

**Comment by sophie-h** [comment]
> You don't want every one of our libraries to have to make a super obvious reference to GTK/GNOME, that gets tired very quickly.

Yeah, I personally I would only be keen on staying away from looking too much like 'only like rust'.

The pink version also works for me. Expecting it to be a bit more controversial though. 

![download (21)](https://user-images.githubusercontent.com/3466497/120811579-69e90f80-c54c-11eb-8056-b93cf57d1ce0.png)

**Comment by GuillaumeGomez** [comment]
I like the pink version too. :)

**Comment by Hofer-Julian** [comment]
+1 for pink.

Alternatively, the red one 😊

**Comment by sdroege** [comment]
Pink, red, blue seems all good to me :)

**Comment by sophie-h** [comment]
My impression is there is a tendency towards pink within active contributors. @bilelmoussaoui was unhappy that ferris isn't cute anymore. On the chat people wanted to throw in GTK symbols.

I would suggest the following: We are going with @bertob's version of the icon. Reasons: I don't think we can get ferris cute for 32x32px. Neither will there be aditionals symbols for GTK in 32x32px. Also, trademark and the question if we actually want a GTK symbol are not settled.

Maybe we will have a large variant of the logo one day. But I don't see that it will happen anytime soon.

Any thoughts?

**Comment by GuillaumeGomez** [comment]
Sounds good to me.

**Comment by sophie-h** [comment]
@bertob we have a go for the pink/purple variant. Can you finalize that version?

**Comment by bertob** [comment]
Some variants with purple:

**Comment by bilelmoussaoui** [comment]
Oh I like the three last ones

**Comment by sdroege** [comment]
Oh no, now it's hard to decide again :) I like them all 4 but the ones with gradient a bit more.

**Comment by GuillaumeGomez** [comment]
I like the one with pink gradient on top (the second one starting from the right).

**Comment by sophie-h** [comment]
> I like the one with pink gradient on top (the second one starting from the right).

@bertob can you send this one as svg?

**Comment by bertob** [comment]
Pushed the SVG here: https://gitlab.gnome.org/Teams/Design/library-icons/-/blob/master/gtk-rs.svg

**Comment by sophie-h** [comment]
Thanks @bertob. Since it is already on gtk-rs.org I guess we can close?

**Comment by bilelmoussaoui** [comment]
Before we close this, it seems like the 48px version of the logo looks very small on the docs 
![image](https://user-images.githubusercontent.com/7660997/121098797-e9017080-c7f6-11eb-9e56-25d8fc876361.png)

while with 96px it looks much better
![image](https://user-images.githubusercontent.com/7660997/121098826-fb7baa00-c7f6-11eb-9d49-e6b4c0479273.png)

do you think it's possible to provide us with a larger variant of the icon? :)

**Comment by sophie-h** [comment]
Fixed via gtk-rs/gtk-rs.github.io#209
