### ISSUE TITLE
Agree on stability statement for crates

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/release#147]
I already relaxed the statement a bit

```diff
- //! The library is a work in progress: expect missing functionality and breaking
- //! changes.
+ //! The library is a work in progress. Expect breaking changes between releases.
```

However, it still did not resonate with everyone.

Personally, I think that 'work in progress' sounds a bit harsh for the quality of gtk-rs. But still, until 1.0 there will be API breakage I guess?

**Comment by GuillaumeGomez** [comment]
Even after 1.0, there will still be breakage. Personally, I'd simply remove it.

**Comment by sdroege** [comment]
I agree, I would also remove it. The crates are as stable as those crates that release a new major release (1.0, 2.0, etc) every year or so :shrug:

**Comment by sophie-h** [comment]
API changes are allowed between 0.x versions in SemVer. Therefore this would be expected based on SemVer.

**Comment by sdroege** [comment]
Rust's version of SemVer treats `0.x.y` as `x.y` so that's all expected, yes :)

**Comment by bilelmoussaoui** [comment]
I agree that we should drop that

**Comment by GuillaumeGomez** [comment]
Do you want to send the PR @sophie-h ?

**Comment by sophie-h** [comment]
Done
