### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/release#177]
Previous release issue was #137.

Before next release we need:

 * [x] Update all crates to 1.56 and 2021 edition
 * [x] Change namespacing of `NONE` (https://github.com/gtk-rs/gir/issues/1252)
 * [x]  #176 
 * [x]  Sync releases with gstreamer-rs (@slomo), relm4 (@aaronerhardt), libadwaita-rs (@bilelmoussaoui) and also mention those in the release blog post
 * [ ] **gtk-rs-core**: 0.15.0 milestone (https://github.com/gtk-rs/gtk-rs-core/milestone/2)
 * [ ] **gtk4**: 0.4 milestone (https://github.com/gtk-rs/gtk4-rs/milestone/4)
 * [ ] **gtk3**: 0.15 milestone (https://github.com/gtk-rs/gtk3-rs/milestone/2)
 * [ ] **gstreamer-rs**: 0.18.0 milestone (https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/milestones/2)
 * [ ] https://github.com/gtk-rs/gir/issues/1261

**Comment by bilelmoussaoui** [comment]
Made a new issue for next release https://github.com/gtk-rs/release/issues/189
