### ISSUE TITLE
Proposal for new release process supporting multiple versions

### ISSUE THREAD

**Issue by talklittle** [gtk-rs/release#21]
Currently the release process only supports a single version at a time, with no possibility to backport bugfixes to older releases.

For example, there may be many features and fixes going into a `gtk` crate version 0.7.0 from 0.6.0. Behavior can break between the two versions. The current release process does not have a way to support both an 0.7.x and 0.6.x release simultaneously; all fixes would be restricted to the 0.7.x line.

The main issue is the branch structure. @sdroege proposed in https://github.com/gtk-rs/glib/pull/294 that rather than having a `master` and `crate` branch per repository, it could be expanded to `master` and `0.6.x` branch and `0.7.x` branch, adding a new branch for each feature release. Then bugfixes could be backported as desired from `master` or `0.7.x` back to the `0.6.x` branch. (And remove the `crate` branch.)

Of course this branch structure would not require maintainers to begin supporting more old versions; but it would be nice to have the option, in case that becomes desirable in the future.

The release process would be:

1. `master` branch always contains an alpha version, e.g. `0.7.0-alpha`
2. When it's time to release 0.7.0, create the branch `0.7.x` from `master`
3. On the `0.7.x` branch, change the version from `0.7.0-alpha` to `0.7.0`
4. On the `master` branch, change the version from `0.7.0-alpha` to `0.8.0-alpha`
5. Publish to crates.io from the relevant branch, `0.7.x`
6. Future bugfixes can be cherry-picked from `master` or other places back into `0.7.x` branch, and version bumped to `0.7.1` for a bugfix release

**Comment by GuillaumeGomez** [comment]
Having such a system is quite heavy however I intended to *start* thinking about it after the 1.0 release (some day...). It takes already a huge amount of time to maintain `gtk-rs` and having this system would only make it even more difficult.

**Comment by sdroege** [comment]
I proposed this before and @GuillaumeGomez prefers how he currently does it and he's the one doing releases :) But that's basically how I do the releases of the GStreamer bindings, and also how GStreamer itself is doing it successfully since a decade or so

**Comment by sdroege** [comment]
Also it does not really increase workload in my case (for 12+ repositories in case of GStreamer, and similar amount for GStreamer bindings). It's just a different workflow

**Comment by EPashkin** [comment]
As I remember there problem with referencing crate by git if it has version, that newer that on crates.io.
So "On the master branch, change the version from 0.7.0-alpha to 0.8.0-alpha" maybe not good.
@sdroege maybe you don't have this problem as all your crates in same repo?

**Comment by sdroege** [comment]
> As I remember there problem with referencing crate by git if it has version, that newer that on crates.io.

There's not really a problem there (make sure to run "cargo update" as usual when changing versions though), it's just like there would be multiple versions on crates.io. But as usual you need to make sure that there are no conflicting version requirements between your Cargo.toml and your dependencies.

(Also my things are in two repositories)

**Comment by sdroege** [comment]
Also if you check, basically everybody is doing it like that. For example check hyper

**Comment by GuillaumeGomez** [comment]
I really don't like playing with multiple branches. Tags are there for this. For me, the version on the `master` branch doesn't matter and the `crate` branch should be what we have on `crates.io`. All of this is up to debate but I have to admit that I'm not very motivated by handling things this way. :-/

**Comment by sdroege** [comment]
Tags are for releases, branches are for separate "development" lines. I.e. you would have one for active development where everything can be broken (master), and then 0.4, etc branches that only get bugfixes as needed and are used for making releases. Basically like your crate branch nowadays, but versioned with the release series it is for.

And at the same time versions in the Cargo.toml of each branch are reflecting that

**Comment by GuillaumeGomez** [comment]
Actually, with your explanations, having a branch for every published version of the crate makes sense. It'll require quite the update for my release script but that seems doable pretty quickly with not much. So in my head:

 * create a new branch from the previous version which will be named after the release version number
 * create another branch from this new branch where I'll push the changes
 * create a PR from the second branch to the first one (it allows confirmation reviews, which is quite useful)
 * merge everything and keep the first branch

Does this scenario looks good?

**Comment by sdroege** [comment]
Not a branch for every published version, but for each "release series". So for 0.3, 0.4, 0.5, etc. In there you would then do the 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, etc releases and create tags for them.

**Comment by talklittle** [comment]
@GuillaumeGomez I think those steps are not really necessary. You can branch directly from `master` to your new release branch `0.7.x` if you are about to release version 0.7.0.

I would not branch from a previous version branch, like branching from `0.6.x` to `0.7.x`, because the previous branch `0.6.x` may contain extra backported commits that might not merge cleanly with `master`.

Supposedly someone already reviewed the PRs for each feature being merged into `master`, so another PR of the whole change seems superfluous IMO.

**Comment by GuillaumeGomez** [comment]
Well, that's a huge mess and the very reason why I'm basically against it. I can't just make a release from `master`, I need to merge it into the current `crate` branch otherwise the cargo file just becomes a huge mess and I have to fix it by hand. For all crates. And believe me: I don't want to do it.

**Comment by sdroege** [comment]
That's why you do the release from the e.g. 0.3 branch, never from master :)

**Comment by GuillaumeGomez** [comment]
Yes but a new branch serie should be created from `master` if I understood correctly. Which also means that I'll have to update all `Cargo.toml` files by hand. Or did I miss anything?

**Comment by sdroege** [comment]
Yes you would create a new branch from master. master would always point at GIT versions of things, the branches would point at the things released on crates.io. So you would have to update the version number in Cargo.toml by hand and also point the dependencies to the actual versions.

But you have to do that now anyway or not? Or your script is doing it, so it could also be used for doing that when branching from master.

**Comment by GuillaumeGomez** [comment]
My script is "doing it". But in a stupid way, it'd require a great update to make it work globally (not very difficult though but still would have have to be done). That's clearly something I'd like to avoid.

**Comment by talklittle** [comment]
There's also the [cargo-edit](https://github.com/killercup/cargo-edit) crate that may help with modifying the Cargo.toml files from the command line or by Python script.

**Comment by GuillaumeGomez** [comment]
So, to sums all this up: I'll do it in the future (very likely *after* the 1.0). But for the moment, I don't intend to support older versions of the crates. We fix bugs for latest versions.

**Comment by sdroege** [comment]
> My script is "doing it". But in a stupid way, it'd require a great update to make it work globally (not very difficult though but still would have have to be done). That's clearly something I'd like to avoid.

How I'm doing it currently is by simply invoking `sed` in the right way after branching. It's not really work.

**Comment by sdroege** [comment]
> So, to sums all this up: I'll do it in the future (very likely after the 1.0). But for the moment, I don't intend to support older versions of the crates. We fix bugs for latest versions.

It's not really about providing fixes for older versions, at least for me. But about having the versions in a structured way in GIT and a simple way of backporting things to the *current* release series by having a branch for that. And having the Cargo.toml in each branch with the correct version and dependencies

**Comment by GuillaumeGomez** [comment]
> How I'm doing it currently is by simply invoking `sed` in the right way after branching. It's not really work.

```toml
[dependencies.gobject-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"
```

Becomes:

```toml
gobject-sys = "0.5.0"
```

Easy transformation but still requires to parse things a bit. Also, I **really** don't like relying on platform specific tools, `cargo-edit` seems like a better idea to do this (even though I won't use it).

> It's not really about providing fixes for older versions, at least for me. But about having the versions in a structured way in GIT and a simple way of backporting things to the current release series by having a branch for that. And having the Cargo.toml in each branch with the correct version and dependencies

For the moment, almost every release is a major one so having a release serie doesn't make much sense.

**Comment by sdroege** [comment]
In my case it's
```
gobject-sys = { git="...", version="0.5.0" }
```
to
```
gobject_sys = "0.5.0"
```

**Comment by GuillaumeGomez** [comment]
We like having multiple lines. :stuck_out_tongue:

**Comment by sdroege** [comment]
> For the moment, almost every release is a major one so having a release serie doesn't make much sense.

I think that's mostly because with the current scheme it's difficult to make bugfix releases. You know that I was asking for bugfix releases a few times in the past already for specific fixes.

In case of the GStreamer bindings, it's a matter of 5 minutes to do a bugfix release now and I'm doing that whenever enough useful fixes have accumulated.
