### ISSUE TITLE
Proposal for change strategy for version update in Cargo.tom

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/release#22]
Currently we (script) open single crate Cargo.toml, iterate through dependencies and increase it depending by `UpdateType` (major/medium/minor), then same process repeated for all crates.

I propose separate version increasing and applying:
- Add config with versions for all your crates (maybe just to `consts.CRATE_LIST`)
- On release first thing is update this config by release type (`UpdateType`) or even manually if we need update only one crate
- For each crates we synchronize version with configured (for both package version and dependencies)

With this we can handle versioning more independently.
Also for one crate will be used same version in all dependents.

cc @GuillaumeGomez, @sdroege

**Comment by EPashkin** [comment]
@GuillaumeGomez What you think about this?

**Comment by GuillaumeGomez** [comment]
I planned to talk about this in the next rust+GNOME hackfest (if you can/want to come, just send me an email, it'd nice to have you with us). @sdroege has ideas about this and what he proposed sounded good. In here, I'm not so sure to see what is the advantage of this system...

**Comment by EPashkin** [comment]
Thanks, for not forgetting about this issue.
I don't plan to go, so I leave the decision to you two.

**Comment by EPashkin** [comment]
@GuillaumeGomez How about use `ours` option for `recursive` merge strategy for merging master into crate:
`git merge -s recursive -X ours master`
It removes merge conflict in `Crate.toml` but leaves nonconflicting changes

**Comment by EPashkin** [comment]
Bad that on current gtk it remove `lazy_static = "1.0"` too :(
