### ISSUE TITLE
Check if bug "gir-files/*" comes from here

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/release#32]
It adds ` = ` at the end of the line?

**Comment by EPashkin** [comment]
Probably from here?

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/release/blob/master/src/my_toml.py#L18

**Comment by GuillaumeGomez** [comment]
To be confirmed but it's very likely. I'll take a look once the release is done.
