### ISSUE TITLE
Create multiple tags if more than one crate in a repository

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/release#49]
In cairo, sourceviez and sys repositories, multiple crates are in one repository, which is problematic for the tagging. I think we should put sys crates behind a tag like `crate-sys-version` and don't change anything for "main" crate.

Original discussion can be found here: https://github.com/gtk-rs/sys/pull/109

**Comment by GuillaumeGomez** [comment]
Does it seem ok like this for you @EPashkin ?

**Comment by EPashkin** [comment]
Yes.

**Comment by GuillaumeGomez** [comment]
Cool! I'll send a PR soon then.

**Comment by EPashkin** [comment]
Thanks in advance.
