### ISSUE TITLE
Skip CI for generated PRs

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/release#50]
.. to minimize its queue.
Both [travis](https://coderwall.com/p/f7fusq/how-to-skip-making-a-build-in-travis-ci) and [appveyor](https://www.appveyor.com/docs/how-to/filtering-commits/#skip-commits) seems understand "[ci skip]" in commit message.

@GuillaumeGomez, @sdroege what you think?

**Comment by GuillaumeGomez** [comment]
Sounds good to me! :+1:

**Comment by sdroege** [comment]
What are generated PRs?

**Comment by GuillaumeGomez** [comment]
All the ones which start with `[release] `.

**Comment by sdroege** [comment]
Sure
